/* import { Types } from 'mongoose';

export const meetups = [
  {
    _id: new Types.ObjectId(),
    title: 'AI och Framtidens Teknik',
    description: 'En kväll där vi diskuterar AI, innovation och hur tekniken förändrar vår vardag.',
    category: 'Teknik',
    location: { city: 'Stockholm', address: 'Sveavägen 12', lat: 59.334, long: 18.063 },
    date: [new Date('2025-11-15')],
    time: '18:00',
    capacity: 40,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Webbutveckling för Nybörjare',
    description:
      'En introduktion till HTML, CSS och JavaScript. Perfekt för dig som vill börja koda.',
    category: 'Teknik',
    location: { city: 'Göteborg', address: 'Avenyn 25', lat: 57.7089, long: 11.9746 },
    date: [new Date('2025-11-18')],
    time: '17:30',
    capacity: 25,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Digital Foto & Bildredigering',
    description: 'Vi går igenom hur man tar bättre bilder och redigerar med Lightroom.',
    category: 'Teknik',
    location: { city: 'Malmö', address: 'Storgatan 20', lat: 55.605, long: 13.0038 },
    date: [new Date('2025-12-02')],
    time: '18:00',
    capacity: 30,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Spelutveckling med Unity',
    description: 'Bygg ditt första spel med Unity – vi går igenom grunderna i 2D-spel.',
    category: 'Teknik',
    location: { city: 'Uppsala', address: 'Teknikgatan 4', lat: 59.858, long: 17.6389 },
    date: [new Date('2025-11-25')],
    time: '19:00',
    capacity: 20,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Robotik och Automation Meetup',
    description: 'En interaktiv kväll med fokus på robotar, sensorer och IoT-lösningar.',
    category: 'Teknik',
    location: { city: 'Lund', address: 'Scheelevägen 2', lat: 55.704, long: 13.191 },
    date: [new Date('2025-12-08')],
    time: '17:00',
    capacity: 25,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: new Types.ObjectId(),
    title: 'Italiensk Matlagning – Pasta från grunden',
    description: 'Lär dig göra färsk pasta med enkel tomatsås. Perfekt för hemmakocken.',
    category: 'Matlagning',
    location: { city: 'Stockholm', address: 'Kungsholmen 14', lat: 59.33, long: 18.05 },
    date: [new Date('2025-11-20')],
    time: '17:00',
    capacity: 15,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Vinprovning för Nybörjare',
    description: 'En kväll med goda viner och tips om hur du matchar dem med mat.',
    category: 'Matlagning',
    location: { city: 'Malmö', address: 'Norra Vallgatan 6', lat: 55.606, long: 13.001 },
    date: [new Date('2025-12-01')],
    time: '18:00',
    capacity: 20,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Vegansk Matlagning',
    description: 'Upptäck enkla och smakrika veganska rätter med lokala råvaror.',
    category: 'Matlagning',
    location: { city: 'Göteborg', address: 'Haga Nygata 12', lat: 57.705, long: 11.959 },
    date: [new Date('2025-12-05')],
    time: '17:30',
    capacity: 18,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Sushikurs – Rulla som ett proffs',
    description: 'Lär dig grunderna i att göra sushi hemma. Allt material ingår!',
    category: 'Matlagning',
    location: { city: 'Umeå', address: 'Storgatan 33', lat: 63.825, long: 20.263 },
    date: [new Date('2025-12-12')],
    time: '18:30',
    capacity: 12,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Julbak & Glöggkväll',
    description: 'Vi bakar lussekatter, pepparkakor och provar olika glöggsorter.',
    category: 'Matlagning',
    location: { city: 'Linköping', address: 'Kungsgatan 5', lat: 58.41, long: 15.62 },
    date: [new Date('2025-12-19')],
    time: '17:00',
    capacity: 25,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: new Types.ObjectId(),
    title: 'Kreativ Pysselkväll',
    description: 'Kom och skapa julkort, pynt och DIY-dekorationer i en mysig miljö.',
    category: 'Pyssel',
    location: { city: 'Stockholm', address: 'Södermalm 21', lat: 59.318, long: 18.066 },
    date: [new Date('2025-12-02')],
    time: '18:00',
    capacity: 20,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Keramik Workshop',
    description: 'Lär dig dreja och skapa din egen kopp eller skål.',
    category: 'Pyssel',
    location: { city: 'Göteborg', address: 'Magasinsgatan 10', lat: 57.703, long: 11.965 },
    date: [new Date('2025-12-09')],
    time: '17:30',
    capacity: 15,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Stick- och Virkkväll',
    description: 'En social kväll för alla som gillar att sticka, virka eller lära sig grunderna.',
    category: 'Pyssel',
    location: { city: 'Uppsala', address: 'Syateljén 2', lat: 59.858, long: 17.6389 },
    date: [new Date('2025-12-10')],
    time: '18:00',
    capacity: 25,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Akvarellmålning för Nybörjare',
    description: 'Grundkurs i akvarellmålning. Material ingår.',
    category: 'Pyssel',
    location: { city: 'Malmö', address: 'Kreativgatan 3', lat: 55.605, long: 13.0038 },
    date: [new Date('2025-12-14')],
    time: '16:00',
    capacity: 18,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Julkrans Workshop',
    description: 'Bind din egen krans till dörren med granris och dekorationer.',
    category: 'Pyssel',
    location: { city: 'Lund', address: 'Floravägen 5', lat: 55.704, long: 13.191 },
    date: [new Date('2025-12-17')],
    time: '17:00',
    capacity: 20,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: new Types.ObjectId(),
    title: 'Board Game Night',
    description: 'En kväll full av brädspel, snacks och skratt!',
    category: 'Gaming',
    location: { city: 'Stockholm', address: 'Gamla Stan 8', lat: 59.325, long: 18.07 },
    date: [new Date('2025-12-05')],
    time: '19:00',
    capacity: 30,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'LAN-Party Winter Edition',
    description: 'Ta med din dator och spela hela natten! Vi bjuder på pizza.',
    category: 'Gaming',
    location: { city: 'Göteborg', address: 'Datahallen 7', lat: 57.708, long: 11.974 },
    date: [new Date('2025-12-20')],
    time: '20:00',
    capacity: 50,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Retro Gaming Meetup',
    description: 'Testa gamla klassiker som Mario Kart, Sonic och Street Fighter.',
    category: 'Gaming',
    location: { city: 'Malmö', address: 'Spelgatan 2', lat: 55.604, long: 13.002 },
    date: [new Date('2025-12-13')],
    time: '18:30',
    capacity: 35,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    title: 'Quiz & Karaoke Night',
    description: 'Kom själv eller med vänner – en kväll fylld med musik, frågesport och skratt.',
    category: 'Nöje',
    location: { city: 'Linköping', address: 'Kungsgatan 11', lat: 58.41, long: 15.62 },
    date: [new Date('2025-12-07')],
    time: '19:00',
    capacity: 40,
    registrations: [],
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
 */
